# -*- coding: utf-8 -*-
"""MonteCarlo2D.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HQRbEWjZST3MP_FtuoyS3por8NWpFIzx
"""

from random import*
import numpy as np
import sympy as sy
import pandas as pd
from math import*
np.random.seed(132)

l1 = []
l2 = []
l3 = []
l4 = []
l5 = []
l6 = []
l7 = []
l8 = []

a = 1
b = 3
c = 2
d = 4
n1 = 10
n2 = 100
n3 = 1000
n4 = 10000

for i in range(n1):
  x = np.random.uniform(a,b)
  y = np.random.uniform(c,d)
  l1.append(x)
  l2.append(y)
for i in range(n2):
  k = np.random.uniform(a,b)
  q = np.random.uniform(c,d)
  l3.append(k)
  l4.append(q)
for i in range(n3):
  u = np.random.uniform(a,b)
  v = np.random.uniform(c,d)
  l5.append(u)
  l6.append(v)
for i in range(n4):
  s = np.random.uniform(a,b)
  t = np.random.uniform(c,d)
  l7.append(s)
  l8.append(t)

def f(z,w):
  return 9*(z**3)*(w**2)

soma1 = 0
soma2 = 0
soma3 = 0
soma4 = 0
for i in range(n1):
  soma1 = soma1 + f(l1[i],l2[i])
for i in range(n2):
  soma2 = soma2 + f(l3[i],l4[i])
for i in range(n3):
  soma3 = soma3 + f(l5[i],l6[i])
for i in range(n4):
  soma4 = soma4 + f(l7[i],l8[i])

I_n1 = soma1*(fabs(b-a)*fabs(d-c))/n1
I_n2 = soma2*(fabs(b-a)*fabs(d-c))/n2
I_n3 = soma3*(fabs(b-a)*fabs(d-c))/n3
I_n4 = soma4*(fabs(b-a)*fabs(d-c))/n4
print(f"Integral para {n1} amostras = {I_n1:.2f}")
print(f"Integral para {n2} amostras = {I_n2:.2f}")
print(f"Integral para {n3} amostras = {I_n3:.2f}")
print(f"Integral para {n4} amostras = {I_n4:.2f}")

I_v = 3360
MC = pd.DataFrame({'n':[n1,n2,n3,n4], 'Integral': [I_n1,I_n2,I_n3,I_n4], 'Erro:': [fabs(I_v-I_n1), fabs(I_v-I_n2),fabs(I_v-I_n3),fabs(I_v-I_n4)]})
print(MC)